# This is a config for E2B sandbox template.
# You can use template ID (ihrwmzi4mt1tez4t93jj) or template name (vibe-testa-nextjs-9) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-testa-nextjs-9") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-testa-nextjs-9") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-testa-nextjs-9')

team_id = "64453675-cfcb-4ee2-9bb7-dbb6a706119f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-testa-nextjs-9"
template_id = "ihrwmzi4mt1tez4t93jj"
